CREATE TABLE POMODORO_USERS (
  USER_ID       VARCHAR2(20) PRIMARY KEY,
  USER_PASSWORD VARCHAR2(20)
);

CREATE TABLE POMODOROS (
  POMODORO_ID   NUMBER AUTO_INCREMENT PRIMARY KEY,
  USER_ID       VARCHAR2(20),
  POMODORO_DATE DATE,
  LENGTH        NUMBER,
  DESCRIPTION   VARCHAR2(60),
  TAG           VARCHAR2(20),
  FOREIGN KEY (USER_ID) REFERENCES POMODORO_USERS (USER_ID)
);

INSERT INTO POMODORO_USERS (USER_ID, USER_PASSWORD)
VALUES ('test', 'test');